{
  self,
  inputs,
  moduleWithSystem,
  ...
}: {
  flake.nixosModules.common = moduleWithSystem ({system}: {
    name,
    pkgs,
    lib,
    config,
    ...
  }: {
    # Where colmena should deploy to, since we do not want to hardcode any IP
    # address, and not every host may have a DNS entry, we instead set this to
    # the same name as in the colmena configuration.
    #
    # Resolution of this name happens through our SSH_CONFIG_FILE, which is
    # generated by opentofu.
    deployment.targetHost = name;

    networking = {
      # Inherited from colmena.nix
      hostName = name;
      # Even though we use AWS security groups, another layer of firewall never
      # hurt anyone.
      firewall.enable = true;
    };

    # Ensures that all logging is done in UTC to make log aggregation easier.
    time.timeZone = "UTC";

    # By only supporting english, we reduce the size of our system closure a
    # bit. This comes at the cost of a higher initial build time since many
    # derivations depend on the locales.
    i18n.supportedLocales = ["en_US.UTF-8/UTF-8" "en_US/ISO-8859-1"];

    boot = {
      # On reboot, delete the contents of /tmp
      tmp.cleanOnBoot = true;

      # Mostly useful for debugging failed boots in the AWS console.
      kernelParams = ["boot.trace"];

      # Ensure /boot never gets too big, and we don't keep referencing old NixOS
      # versions forever.
      # Once removed from the Grub configuration, old NixOS versions will
      # automatically be garbage collected.
      loader.grub.configurationLimit = 10;
    };

    # Mostly utilities to setup and debug machines. Plus everyones favorite
    # editors.
    environment.systemPackages = with pkgs; [
      awscli2
      bat
      bind
      # Useful for the `growpart` utility, which can be used after resizing
      # a volume.
      cloud-utils
      di
      dnsutils
      fd
      fx
      file
      gitMinimal
      # More of a comprehensive dashboard than htop, but requires more resources
      # and provides no control
      glances
      helix
      # Easily see what's going on with a machine.
      htop
      ijq
      # Diff on steroids
      icdiff
      iptables
      jiq
      jq
      lsof
      neovim
      ncdu
      parted
      pciutils
      procps
      ripgrep
      rsync
      sops
      sysstat
      tcpdump
      tree
    ];

    sops = {
      # Ensure we always read and write things as they are, and not interpret them as YAML or JSON.
      defaultSopsFormat = "binary";

      # This token is required for auth-keys-hub. It requires at least org:read
      # permissions to check team membership.
      secrets.github-token = {
        sopsFile = "${self}/secrets/github-token.enc";
        owner = config.programs.auth-keys-hub.user;
        inherit (config.programs.auth-keys-hub) group;
      };
    };

    programs = {
      # Used by OpenSSH to allow logins with user keys as published on GitHub.
      auth-keys-hub = {
        enable = true;

        # This isn't in nixpkgs yet, so get it from the source.
        package = inputs.auth-keys-hub.packages.${system}.auth-keys-hub;

        # Persist the authorized_keys file across reboots.
        dataDir = "/var/lib/auth-keys-hub";

        github = {
          # We'll allow all members of these teams complete access via SSH.
          teams = ["input-output-hk/node-sre"];

          # For fallback purposes, we also specify some admins, since single
          # users don't require a GitHub token to update.
          users = ["manveru" "johnalotoski"];

          # The token from above.
          tokenFile = config.sops.secrets.github-token.path;
        };
      };

      # For ad-hoc terminal sharing we use tmux, start a session with `tmux`,
      # then other people join with `tmux attach`.
      tmux = {
        enable = true;
        aggressiveResize = true;
        clock24 = true;
        escapeTime = 0;
        historyLimit = 10000;
        newSession = true;
      };
    };

    services = {
      # For keeping our clock accurate, we use chrony.
      # There are a number of reasons why we prefer chrony over alternatives,
      # but generally it performs better within VMs and is more resilient to
      # changes in network and temperature.
      # https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/system_administrators_guide/ch-configuring_ntp_using_the_chrony_suite#sect-differences_between_ntpd_and_chronyd
      chrony = {
        enable = true;
        extraConfig = "rtcsync";
        enableRTCTrimming = false;
      };

      # Disable since we use chrony
      services.ntp.enable = false;

      cron.enable = true;
      fail2ban.enable = true;

      openssh = {
        enable = true;
        settings = {
          PasswordAuthentication = false;
          RequiredRSASize = 2048;
          PubkeyAcceptedAlgorithms = "-*nist*";
        };
      };

      grafana-agent = {
        enable = true;
        extraFlags = ["-disable-reporting"];
        settings = {
          integrations = {
            prometheus_remote_write = [{url = "http://127.0.0.1:8080/mimir/api/v1/push";}];
            node_exporter = {
              set_collectors = [
                "boottime"
                "conntrack"
                "cpu"
                "diskstats"
                "filefd"
                "filesystem"
                "loadavg"
                "meminfo"
                "netdev"
                "netstat"
                "os"
                "sockstat"
                "softnet"
                "stat"
                "time"
                "timex"
                "uname"
                "vmstat"
              ];
            };
          };

          metrics = {
            configs = [
              {
                name = "integrations";
                remote_write = [{url = "http://127.0.0.1:8080/mimir/api/v1/push";}];
                scrape_configs = [
                  {
                    job_name = "blackbox";
                    metrics_path = "/probe";
                    params.module = ["https_2xx"];
                    scrape_interval = "1m";
                    static_configs = let
                      blackboxPath = (inputs."cardano-${name}") + "/flake/terraform/grafana/blackbox/blackbox.nix-import";
                    in
                      lib.mkIf (builtins.hasAttr "cardano-${name}" inputs && builtins.pathExists blackboxPath)
                      [
                        {
                          targets = import blackboxPath;
                        }
                      ];
                    relabel_configs = [
                      {
                        source_labels = ["__address__"];
                        target_label = "__param_target";
                      }
                      {
                        source_labels = ["__param_target"];
                        target_label = "instance";
                      }
                      {
                        replacement = "127.0.0.1:9115";
                        target_label = "__address__";
                      }
                    ];
                  }
                  {
                    job_name = "prometheus";
                    scheme = "http";
                    static_configs = [
                      {
                        targets = ["${config.services.prometheus.listenAddress}:${toString config.services.prometheus.port}"];
                      }
                    ];
                    metrics_path = "/metrics";
                  }
                  {
                    job_name = "mimir";
                    scheme = "http";
                    static_configs = [
                      {
                        targets = ["${config.services.mimir.configuration.server.http_listen_address}:${toString config.services.mimir.configuration.server.http_listen_port}"];
                      }
                    ];
                    metrics_path = "/mimir/metrics";
                  }
                  {
                    job_name = "grafana";
                    scheme = "http";
                    static_configs = [
                      {
                        targets = ["${config.services.grafana.settings.server.http_addr}:${toString config.services.grafana.settings.server.http_port}"];
                      }
                    ];
                    metrics_path = "/metrics";
                  }
                ];
              }
            ];
          };
        };
      };
    };

    system = {
      # Ensure the nixpgs repo is persisted on the machine itself for easier
      # debugging.
      extraSystemBuilderCmds = ''
        ln -sv ${pkgs.path} $out/nixpkgs
      '';

      # This provides a nice summary for all the things that change between deployments.
      # For example:
      # playground | [U.] #20 linux 6.1.64, 6.1.64-modules-shrunk -> 6.1.72, 6.1.72-modules-shrunk
      activationScripts.diff = {
        supportsDryActivation = true;
        text = ''
          ${pkgs.nvd}/bin/nvd --nix-bin-dir=${pkgs.nix}/bin diff /run/current-system "$systemConfig"
        '';
      };
    };

    nix = {
      registry.nixpkgs.flake = inputs.nixpkgs;
      optimise.automatic = true;
      gc.automatic = true;

      settings = {
        auto-optimise-store = true;
        builders-use-substitutes = true;
        experimental-features = ["nix-command" "fetch-closure" "flakes" "cgroups"];
        keep-derivations = true;
        keep-outputs = true;
        max-jobs = "auto";
        show-trace = true;
        substituters = ["https://cache.iog.io"];
        system-features = ["recursive-nix" "nixos-test"];
        tarball-ttl = 60 * 60 * 72;
        trusted-public-keys = ["hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ="];
      };
    };

    hardware.enableRedistributableFirmware = true;

    system.stateVersion = "23.05";

    systemd = {
      services = {
        # Remove the bootstrap key after 1 week in favor of auth-keys-hub use
        remove-ssh-bootstrap-key = {
          wantedBy = ["multi-user.target"];
          after = ["network-online.target"];

          serviceConfig = {
            Type = "oneshot";

            ExecStart = lib.getExe (pkgs.writeShellApplication {
              name = "remove-ssh-bootstrap-key";
              runtimeInputs = with pkgs; [fd gnugrep gnused];
              text = ''
                if ! [ -f /root/.ssh/.bootstrap-key-removed ]; then
                  # Verify auth keys is properly hooked into sshd
                  if ! grep -q 'AuthorizedKeysCommand /etc/ssh/auth-keys-hub --user %u' /etc/ssh/sshd_config; then
                    echo "SSH daemon authorized keys command does not appear to have auth-keys-hub installed"
                    exit
                  fi

                  if ! grep -q 'AuthorizedKeysCommandUser ${config.programs.auth-keys-hub.user}' /etc/ssh/sshd_config; then
                    echo "SSH daemon authorized keys command user does not appear to be using the ${config.programs.auth-keys-hub.user} user"
                    exit
                  fi

                  # Ensure at least 1 ssh key is declared outside of auth-keys-hub
                  if ! grep -q -E '^ssh-' /etc/ssh/authorized_keys.d/root &> /dev/null; then
                    echo "You must declare at least 1 authorized key via users.users.root.openssh.authorizedKeys attribute before the bootstrap key will be removed"
                    exit
                  fi

                  # Allow 1 week of bootstrap key use before removing it
                  if fd --quiet --changed-within 7d authorized_keys /root/.ssh; then
                    echo "The root authorized_keys file has been changed within the past week; waiting a little longer before removing the bootstrap key"
                    exit
                  fi

                  # Remove the bootstrap key and set a marker
                  echo "Removing the bootstrap key from /root/.ssh/authorized_keys"
                  sed -i '/bootstrap/d' /root/.ssh/authorized_keys
                  touch /root/.ssh/.bootstrap-key-removed
                fi
              '';
            });
          };
        };
      };

      timers = {
        remove-ssh-bootstrap-key = {
          wantedBy = ["timers.target"];
          timerConfig = {
            OnCalendar = "daily";
            Unit = "remove-ssh-bootstrap-key.service";
          };
        };

        # Enforce accurate 10 second sysstat sampling intervals
        sysstat-collect.timerConfig.AccuracySec = "1us";
      };
    };
  });
}
